vp6242:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains: # Required because we're controlling an effort interface
      joint1: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
      joint2: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
      joint3: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
      joint4: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
      joint5: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
      joint6: {p: 80.0,  d: 50.0, i: 1, i_clamp: 0.01}
    allow_partial_joints_goal: True
  gripper_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_finger1_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
