vp6242:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 80.0, i: 0.01, d: 50.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 80.0, i: 0.01, d: 50.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 80.0, i: 0.01, d: 50.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 80.0, i: 0.01, d: 50.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 80.0, i: 0.01, d: 50.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 80.0, i: 0.01, d: 50.0}
  gripper_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_finger1_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
